version: "3.8"

services:
  server:
    build: ./Server
    network_mode: "host"
    ports:
      - "12345:12345"

  client:
    build: ./Client
    depends_on:
      - server
    network_mode: "host"
    ports:
      - "8080:8080"
